version: '3.7'

services:
 delta_app:
  env_file: .env
  build:
   args:
    user: ${USER}
    uid: ${UID}
   context: ./
   dockerfile: Dockerfile
  image: delta
  container_name: delta-app
  restart: unless-stopped
  working_dir: /usr/share/nginx/html
  volumes:
    - ${WORK_DIR_SRC}:/usr/share/nginx/html
  networks:
    - delta

 delta_db:
  image: mariadb
  container_name: delta-db
  restart: unless-stopped
  environment:
    MYSQL_DATABASE: deltadb
    MYSQL_ROOT_PASSWORD: 123123
    MYSQL_PASSWORD: 123123
    MYSQL_USER: root
  ports:
    - "3500:3306"
  volumes:
  - deltadata:/var/lib/mysql
  networks:
  - delta

 nginx_delta:
  image: nginx
  env_file: .env
  volumes:
  - ${WORK_DIR_SRC}:/usr/share/nginx/html
  - ${WORK_DIR}:/etc/nginx/conf.d
  ports:
  -  "8077:80"
  networks:
  - delta

networks:
  delta:
    driver: bridge

volumes:
 deltadata:
   name: deltadata
   external: true
